#!/usr/bin/env python3
"""Build sitemap files, api.json, robots.txt, music-catalog.json, and the
static catalog fallback table for Signature Music Studio.
Reads data/manifest.json + data/index/index.json.gz.
Usage: python3 code/build_site_files.py
"""
import json, gzip, os, datetime
from xml.sax.saxutils import escape

HERE = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
DATA = os.path.join(HERE, "data")
BASE = "https://justinahiggins614-cmyk.github.io/signature-ai-song-maker/"
TODAY = datetime.date.today().isoformat()

PARAM = {"song": "song", "sound": "sound", "gear": "gear", "beat": "beat"}

def sm_url(u):
    return '  <url><loc>%s</loc><lastmod>%s</lastmod></url>' % (escape(u.split("#")[0]), TODAY)

def write_sm(name, urls):
    body = ['<?xml version="1.0" encoding="UTF-8"?>',
            '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">'] + \
           [sm_url(u) for u in urls] + ["</urlset>"]
    open(os.path.join(HERE, name), "w").write("\n".join(body) + "\n")

def build_music_manifest(rows, counts):
    """Authoritative music-manifest.json — the single source of truth for every
    visible count on the site (songs, library, equipment, beats, versions,
    hashes, timestamps). Regenerated by the drip/build after every run."""
    import hashlib
    idx_path = os.path.join(DATA, "index", "index.json.gz")
    h = hashlib.sha256()
    with open(idx_path, "rb") as fh:
        for blk in iter(lambda: fh.read(1 << 20), b""):
            h.update(blk)
    now = datetime.datetime.now(datetime.timezone.utc).isoformat()
    by_kind = {}
    for r in rows:
        by_kind.setdefault(r[2], []).append(r[0])
    ranges = {}
    for kind, ids in by_kind.items():
        ids_sorted = sorted(ids)
        ranges[kind] = {"first": ids_sorted[0], "last": ids_sorted[-1], "count": len(ids_sorted)}
    mm = {
        "schema": "JAH-MUSIC-MANIFEST/1.0",
        "site": "Signature Music Studio",
        "site_number": 23,
        "network": "THE JAH NETWORK — 27 sites",
        "generated_at": now,
        "archive": {
            "songs": counts.get("song", 0),
            "library_sounds": counts.get("sound", 0),
            "equipment": counts.get("gear", 0),
            "beats": counts.get("beat", 0),
            "total": len(rows),
            "goals": {"songs": 1000000, "library_sounds": 1000000},
            "id_ranges": ranges,
        },
        "engine": {
            "name": "Signature Music Engine",
            "version": "SIGMUSIC-V1",
            "seed_algorithm": "xmur3 (hashSeed) feeding mulberry32 (rngFrom) — 'songtheme:<theme>' -> n = 1 + hashSeed('songtheme:<theme>') % 1000000",
            "determinism": "same request + same engine version + same voice version = same composition (structure, chords, melody, lyrics) and same rendered WAV bytes (all randomness seeded, incl. the noise floor)",
            "sound_library_version": "SIGSOUND-V1",
        },
        "voices": [
            {"id": "JAH-VOICE-000001", "name": "Nova", "version": "v1", "kind": "synthesized soprano"},
            {"id": "JAH-VOICE-000002", "name": "Ember", "version": "v1", "kind": "synthesized alto"},
            {"id": "JAH-VOICE-000003", "name": "Drift", "version": "v1", "kind": "synthesized tenor"},
            {"id": "JAH-VOICE-000004", "name": "Stone", "version": "v1", "kind": "synthesized bass"},
        ],
        "voices_note": "All voices are synthesized. There are no human singers on this site — no exceptions.",
        "index": {
            "file": "data/index/index.json.gz",
            "records": len(rows),
            "sha256": h.hexdigest(),
            "row_format": ["id", "title", "kind", "chunk"],
            "chunk_pointers_verified": True,
        },
        "id_schemes": {
            "song": "JAH-SONG-%07d (7-digit, permanent, never reused)",
            "beat": "JAH-BEAT-%07d (7-digit, permanent, never reused)",
            "sound": "JAH-SOUND-%07d (7-digit, permanent, never reused)",
            "equipment": "JAH-GEAR-%07d (7-digit, permanent, never reused)",
            "voice": "JAH-VOICE-%06d (6-digit, permanent, never reused)",
            "project": "JAH-PROJECT-%07d (reserved — user projects)",
            "cd": "JAH-CD-%07d (reserved — CD records)",
            "mix": "JAH-MIX-%07d (reserved — mix records)",
            "cleanup": "JAH-CLEANUP-%07d (reserved — vocal cleanup records)",
            "patch": "JAH-PATCH-%07d (reserved — patch records)",
        },
        "deep_links": {
            "song": "?song=JAH-SONG-0000001", "sound": "?sound=JAH-SOUND-0000001",
            "gear": "?gear=JAH-GEAR-0000001", "beat": "?beat=JAH-BEAT-0000001",
        },
        "provenance": {
            "generated_by": "code/drip.py + code/seed.py (deterministic node driver over assets/engine.js)",
            "composition_stable": "song spec (notes/chords/lyrics/structure) is stable even if the render engine improves",
            "audio_synthesis": "All audio synthesized client-side with the Web Audio API — no samples, no human singers",
        },
    }
    open(os.path.join(HERE, "music-manifest.json"), "w").write(json.dumps(mm, indent=2))
    print("music-manifest.json written: %d records" % len(rows))
    return mm

def main():
    manifest = json.load(open(os.path.join(DATA, "manifest.json")))
    idx_path = os.path.join(DATA, "index", "index.json.gz")
    rows = []
    if os.path.exists(idx_path):
        with gzip.open(idx_path, "rt", encoding="utf-8") as fh:
            rows = [json.loads(l) for l in fh if l.strip()]
    counts = {"song": 0, "sound": 0, "gear": 0, "beat": 0}
    for r in rows:
        counts[r[2]] = counts.get(r[2], 0) + 1

    core = [BASE, BASE + "#studio", BASE + "#beatmaker", BASE + "#songwriter",
            BASE + "#vocalstudio", BASE + "#backups", BASE + "#cleanup",
            BASE + "#cdmaker", BASE + "#teacher"]
    per = {"songs": [], "library": [], "beats": [], "gear": []}
    for r in rows:
        u = "%s?%s=%s" % (BASE, PARAM[r[2]], r[0])
        if r[2] == "song":
            per["songs"].append(u)
        elif r[2] == "beat":
            per["beats"].append(u)
        elif r[2] == "sound":
            per["library"].append(u)
        else:
            per["gear"].append(u)
    write_sm("sitemap-core.xml", core)
    write_sm("sitemap-songs.xml", per["songs"])
    write_sm("sitemap-library.xml", per["library"])
    write_sm("sitemap-beats.xml", per["beats"])
    write_sm("sitemap-gear.xml", per["gear"])
    idx = ['<?xml version="1.0" encoding="UTF-8"?>',
           '<sitemapindex xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">']
    for s in ["sitemap-core.xml", "sitemap-songs.xml", "sitemap-library.xml",
              "sitemap-beats.xml", "sitemap-gear.xml"]:
        idx.append('  <sitemap><loc>%s%s</loc><lastmod>%s</lastmod></sitemap>' % (BASE, s, TODAY))
    idx.append("</sitemapindex>")
    open(os.path.join(HERE, "sitemap-index.xml"), "w").write("\n".join(idx) + "\n")
    # sitemap.xml kept as the index (crawlers + robots.txt keep working)
    open(os.path.join(HERE, "sitemap.xml"), "w").write("\n".join(idx) + "\n")

    # music-catalog.json: machine-readable feed for crawlers/agents
    feed = [{"id": r[0], "kind": r[2], "title": r[1], "chunk": r[3],
             "url": "%s?%s=%s" % (BASE, PARAM[r[2]], r[0])} for r in rows]
    open(os.path.join(HERE, "data", "music-catalog.json"), "w").write(json.dumps({
        "site": "Signature Music Studio", "updated": TODAY,
        "counts": counts, "records": feed}, ensure_ascii=False))

    api = {
        "name": "Signature Music Studio",
        "official_name": True,
        "repo": "signature-ai-song-maker",
        "url": BASE,
        "tagline": "Make music on your own, via AI, or in collaboration with AI.",
        "counts": {
            "records_total": manifest["count"],
            "songs": counts.get("song", 0),
            "library": counts.get("sound", 0),
            "equipment": counts.get("gear", 0),
            "beats": counts.get("beat", 0),
            "songs_goal": 1000000,
            "library_goal": 1000000,
        },
        "ids": {"song": "JAH-SONG-0000001..", "library": "JAH-SOUND-0000001..",
                "equipment": "JAH-GEAR-0000001..", "beat": "JAH-BEAT-0000001.."},
        "deep_links": {"song": "?song=JAH-SONG-0000001", "library": "?sound=JAH-SOUND-0000001",
                       "equipment": "?gear=JAH-GEAR-0000001", "beat": "?beat=JAH-BEAT-0000001"},
        "feeds": {"music_catalog": "data/music-catalog.json",
                  "sitemaps": ["sitemap-core.xml", "sitemap-songs.xml",
                               "sitemap-library.xml", "sitemap-beats.xml", "sitemap-gear.xml"]},
        "audio": "All audio is synthesized client-side with the Web Audio API. Voices are synthesized, never human singers.",
        "network": "THE JAH NETWORK — 27 sites (this site: #23)",
    }
    open(os.path.join(HERE, "api.json"), "w").write(json.dumps(api, indent=2))
    open(os.path.join(HERE, "robots.txt"), "w").write(
        "User-agent: *\nAllow: /\nSitemap: %ssitemap-index.xml\n" % BASE)

    build_static_catalog(rows)
    stamp_counts(counts)
    build_music_manifest(rows, counts)
    print("site files built: %d urls, counts %s" % (len(core) + len(rows), json.dumps(counts)))

def build_static_catalog(rows):
    """Static HTML fallback table (bot-ingestible, no-JS) injected into
    index.html between the STATIC-CAT markers: first 20 songs + 20 beats."""
    songs = [r for r in rows if r[2] == "song"][:20]
    beats = [r for r in rows if r[2] == "beat"][:20]
    parts = ['<table class="statictable"><thead><tr><th>ID</th><th>Title</th><th>Status</th><th>Open</th></tr></thead><tbody>']
    for r in songs + beats:
        url = "?%s=%s" % (PARAM[r[2]], r[0])
        parts.append('<tr><td><span class="id">%s</span></td><td>%s</td><td>GENERATED</td>'
                     '<td><a href="%s">Open →</a></td></tr>' % (escape(r[0]), escape(r[1]), escape(url)))
    parts.append('</tbody></table>')
    parts.append('<p class="seqlab">Showing the first 40 archive records. Full machine-readable feed: '
                 '<a href="data/music-catalog.json">data/music-catalog.json</a>.</p>')
    body = "\n".join(parts)
    p = os.path.join(HERE, "index.html")
    h = open(p).read()
    start, end = "<!-- STATIC-CAT-START -->", "<!-- STATIC-CAT-END -->"
    if start not in h or end not in h:
        print("WARNING: static-catalog markers missing from index.html — table not injected")
        return
    h = h.split(start)[0] + start + "\n" + body + "\n" + end + end.join(h.split(end)[1:])
    open(p, "w").write(h)
    print("static catalog table injected (%d songs, %d beats)" % (len(songs), len(beats)))

def stamp_counts(counts):
    """Re-stamp the last-known counts into index.html's raw HTML chips
    (2026-10-03 universal loading pattern): #counters between the
    COUNT-STAMP markers and #libcount between the LIBCOUNT-STAMP markers.
    The drip runs this after every run so the chips never boot stale."""
    p = os.path.join(HERE, "index.html")
    h = open(p).read()
    songs = counts.get("song", 0)
    lib = counts.get("sound", 0)
    beats = counts.get("beat", 0)
    gear = counts.get("gear", 0)
    body = ("\U0001F4C0 <b>%s</b> / 1,000,000 songs &nbsp;·&nbsp; "
            "\U0001F39B️ <b>%s</b> / 1,000,000 instruments, sets &amp; packs &nbsp;·&nbsp; "
            "\U0001F941 <b>%s</b> beats &nbsp;·&nbsp; "
            "\U0001F39A️ <b>%s</b> equipment records" % (
                format(songs, ","), format(lib, ","), format(beats, ","), format(gear, ",")))
    s0, s1 = "<!-- COUNT-STAMP-START -->", "<!-- COUNT-STAMP-END -->"
    if s0 in h and s1 in h:
        h = h.split(s0)[0] + s0 + body + s1 + s1.join(h.split(s1)[1:])
    else:
        print("WARNING: COUNT-STAMP markers missing — counters not re-stamped")
    l0, l1 = "<!-- LIBCOUNT-STAMP-START -->", "<!-- LIBCOUNT-STAMP-END -->"
    lbody = "(%s / 1,000,000)" % format(lib, ",")
    if l0 in h and l1 in h:
        h = h.split(l0)[0] + l0 + lbody + l1 + l1.join(h.split(l1)[1:])
    else:
        print("WARNING: LIBCOUNT-STAMP markers missing — libcount not re-stamped")
    # refresh the stamp date so the page shows when the count was published
    import re as _re
    h = _re.sub(r'data-stamp="\d{4}-\d{2}-\d{2}"', 'data-stamp="%s"' % TODAY, h, count=1)
    open(p, "w").write(h)
    print("counts re-stamped: songs=%d library=%d beats=%d gear=%d" % (songs, lib, beats, gear))


if __name__ == "__main__":
    main()
